steps:
# Pulling the latest existing image can make the build process faster as docker uses cache
- name: 'gcr.io/cloud-builders/docker' 
  id: 'Pull'
  entrypoint: 'bash'
  args: [
   '-c', 
   'docker pull gcr.io/$PROJECT_ID/kube-google-cloud:latest || exit 0'
  ]
- name: gcr.io/cloud-builders/docker
  id: 'Build'
  args: [
   'build', 
   '-t', 
   'gcr.io/$PROJECT_ID/kube-google-cloud:$BRANCH_NAME-$COMMIT_SHA',
   '-t', 
   'gcr.io/$PROJECT_ID/kube-google-cloud:latest',
   '.'
  ]
- name: 'gcr.io/cloud-builders/kubectl'
  id: 'Deploy'
  args: ['apply', '-f', 'k8s/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=$_CLUSTER_ZONE'
  - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'
- name: 'gcr.io/cloud-builders/kubectl'
  id: 'Push'
  args: [
   'set', 
   'image', 
   'deployment', 
   'kube-google-cloud', 
   'kube-google-cloud=gcr.io/$PROJECT_ID/kube-google-cloud:$BRANCH_NAME-$COMMIT_SHA'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
# push images to Google Container Registry with tags
images: [
  'gcr.io/$PROJECT_ID/kube-google-cloud:$BRANCH_NAME-$COMMIT_SHA',
  'gcr.io/$PROJECT_ID/kube-google-cloud:latest'
  ]